version: "3"
networks:
  docobase:
    driver: bridge
services:
  app:
    image: docobase/docobase:latest
    networks:
      - docobase
    environment:
      - APP_KEY=your-secret-key # Replace it with your own app key
      - ENCRYPTION_FIELD_KEY=your-secret-key # Replace it with your own app key
      - DB_DIALECT=postgres
      - DB_HOST=postgres
      - DB_DATABASE=docobase
      - DB_USER=docobase
      - DB_PASSWORD=docobase
    volumes:
      - ./storage:/app/docobase/storage
    ports:
      - "13000:80"
    depends_on:
      - postgres
    init: true
  postgres:
    image: postgres:10
    restart: always
    command: postgres -c wal_level=logical
    environment:
      POSTGRES_USER: docobase
      POSTGRES_DB: docobase
      POSTGRES_PASSWORD: docobase
    volumes:
      - ./storage/db/postgres:/var/lib/postgresql/data
    networks:
      - docobase
